### ISSUE TITLE
Autodoc generation fails: searches for local.db in cwd: "doc/"

### ISSUE THREAD

**Issue by daniel-j-h** [spz-signup/spz-signup#25]
The documentation generation fails at the moment, because the autodoc module imports our package. By doing so, the current working directory is doc/ and now the file for the sqlite3 database is assumed to be doc/local.db instead of local.db in the root directory.

**Comment by crepererum** [comment]
Closed by dfbc20c7c13f698e54a4ad2aa5f23212e05ec401

**Comment by daniel-j-h** [comment]
You sure this works again? http://spz.readthedocs.io/en/latest/spz.html looks rather empty.

**Comment by crepererum** [comment]
We don't use RTD anymore, because:
 1. We need docker to generate the docs which works perfectly locally. That's sufficient for our own devs.
 2. The entire (Python) docs system that relies on the evaluation of Python code (and not just the parsing of it) is just broken. I won't spend any more time in fixing a something which does not have any value for anyone here. Build the docs locally.
 3. And for RTD: give developers a way to upload their generated docs. Everything else is just bollocks. (in other words: why should I re-adjust the code for yet-another build-env, apart from dev machines, prod machines and [which has way higher priority] a CI server?)

**Comment by daniel-j-h** [comment]
:+1: with that, but maybe remove the ref. from the readme then :)

**Comment by crepererum** [comment]
:white_check_mark:
