### ISSUE TITLE
Downgradable Test Ratings in UI

### ISSUE THREAD

**Issue by daniel-j-h** [spz-signup/spz-signup#42]
If multiple test results are available (because maybe multiple tests were taken, old results, ...) we pick the best one.  Sometimes students want to downgrade their test results, often because the test was a few years already ago.

There should be a corresponding feature in the UI (in/nearby the test result importer).

See: https://github.com/spz-signup/spz-signup/blob/8cfd6eb93e95d460675d7e729002bd2391cfd660/spz/models.py#L147-L150

**Comment by crepererum** [comment]
That could easily be fixed by changing the score ranges of the courses to overlapping ones. The discussion result was that we do not want over qualified people in our courses except they have a good reason (and therefore have to write an email). If this method is too complicated is a question of how pointless the test system is in general and if people should (by de default) be allowed to attend courses which are below their skill level. I leave this open for now but a fix will require a general discussion + decision.

**Comment by crepererum** [comment]
Fixed, you can now upload `priority` approvals, which override the normal ones. This way you can down- or upgrade people. No user GUI for now, because I don't have enough time to implement yet-another-UI. English department is fine with the current system.
