### ISSUE TITLE
Use official docker images

### ISSUE THREAD

**Issue by tobiasdierich** [spz-signup/spz-signup#73]
We should replace the custom postgres, redis and nginx with the official images from docker hub. At the same time we should upgrade the images.

**Comment by crepererum** [comment]
Some notes on the design choices here:

When I originally created the images, the set of upstream images wasn't as good as it is today. Today, I would also choose an upstream image. But do yourself a favor and choose a tag that pins the major version. That way you automatically pull security updates but can expect less (or even no) breaking changes. 

Where you have to be careful is the configuration, especially for nginx. I would go for a full custom config again.

Also, nginx is way more important to upgrade since it is exposed to the internet while the others are hidden behind the python process (so less likely to be exploited).

**Comment by tobiasdierich** [comment]
Thanks for your comment. I've just created a PR (#78). Images are tagged to their previously used versions and use the same (full-)configs as before. I'll update the images after the upcoming registration phase.
